// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjg2S_NihFycRUVdGqxNKdAVRkuL4Ej7g',
    appId: '1:305072829140:web:eb39bcbf21239542304141',
    messagingSenderId: '305072829140',
    projectId: 'lingobreeze-6d7f9',
    authDomain: 'lingobreeze-6d7f9.firebaseapp.com',
    storageBucket: 'lingobreeze-6d7f9.firebasestorage.app',
    measurementId: 'G-5JKKSGJ1S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqiO69QAZHHGHxkkRncDYevyz59reD5yk',
    appId: '1:305072829140:android:5b216e1b17804d20304141',
    messagingSenderId: '305072829140',
    projectId: 'lingobreeze-6d7f9',
    storageBucket: 'lingobreeze-6d7f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1TeSzmez40QKbNXfxQsK1crjeX6RbQCE',
    appId: '1:305072829140:ios:d8010a4fcd79d5c6304141',
    messagingSenderId: '305072829140',
    projectId: 'lingobreeze-6d7f9',
    storageBucket: 'lingobreeze-6d7f9.firebasestorage.app',
    iosBundleId: 'com.lingobreeze.lingobreeze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1TeSzmez40QKbNXfxQsK1crjeX6RbQCE',
    appId: '1:305072829140:ios:d8010a4fcd79d5c6304141',
    messagingSenderId: '305072829140',
    projectId: 'lingobreeze-6d7f9',
    storageBucket: 'lingobreeze-6d7f9.firebasestorage.app',
    iosBundleId: 'com.lingobreeze.lingobreeze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjg2S_NihFycRUVdGqxNKdAVRkuL4Ej7g',
    appId: '1:305072829140:web:5ed0500d08427b33304141',
    messagingSenderId: '305072829140',
    projectId: 'lingobreeze-6d7f9',
    authDomain: 'lingobreeze-6d7f9.firebaseapp.com',
    storageBucket: 'lingobreeze-6d7f9.firebasestorage.app',
    measurementId: 'G-96G2W3G31S',
  );
}
